version: '3.3'

services:
    #service 1: definition of mysql database
#    db:
#      image: mysql:latest
#      container_name: db
#      environment:
#        - MYSQL_ALLOW_EMPTY_PASSWORD=true
#        - MYSQL_PASSWORD=root
#        - MYSQL_DATABASE=db
#      ports:
#        - "3306:3306"
#      networks:
#        - portfolio-mysql
#      restart: always



    #service 2: definition of your spring-boot app
    backendservice:                        #it is just a name, which will be used only in this file.
      image: portfolio               #name of the image after dockerfile executes
      container_name: portfolio-app  #name of the container created from docker image
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD:
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "9000:9000"                       #docker containter port with your os port
      networks:
        - portfolio-mysql
      restart: always


#      depends_on:                           #define dependencies of this app
#        - db                                #dependency name (which is defined with this name 'db' in this file earlier)
#      environment:
#        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db
#        SPRING_DATASOURCE_USERNAME: user
#        SPRING_DATASOURCE_PASSWORD: password

    #service 3: definition of my react app
    frontendservice:
      image: portfoliofront
      container_name: portfolio-app-front
      environment:
        CHOKIDAR_USEPOLLING: "true"
      volumes:
        - /app/node_modules
        - ./src/main/ui/portfolioFront:/app
      build:
        context: src/main/ui/portfolioFront                          #docker file path (. means root directory)
        dockerfile: Dockerfile
      ports:
        - "80:3000"
      networks:
        - portfolio-mysql

networks:
  portfolio-mysql: